In [1]:
import numpy as np

In [2]:
a = np.array([0,1,2])
b = np.array([5,5,5])
a+b

array([5, 6, 7])

In [3]:
a+5

array([5, 6, 7])

In [5]:
M = np.ones((3,3))
M

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [6]:
M+a 
"""Here the one-dimensional array a is stretched, 
or broadcast across the second dimension in order to match the shape of M.
"""

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [7]:
a = np.arange(3)
b = np.arange(3)[:,np.newaxis]
print(a)
print(b)

[0 1 2]
[[0]
 [1]
 [2]]


In [8]:
a+b #this caused a to stretch into a 3 column mode and b to a 3 row(3 data in a column mode)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])